version: '3.8'

services:
  mysql:
    container_name: mysql-main
    image: mysql:8.0.31
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
